<?php

declare(strict_types=1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230515143702 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE CHAPTER (idChapter INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR(100) NOT NULL, position INTEGER UNSIGNED NOT NULL, updatedAt DATETIME NOT NULL, createdAt DATETIME NOT NULL, mediaVideo VARCHAR(30) DEFAULT NULL, mediaRessource VARCHAR(30) DEFAULT NULL, idCourse INTEGER UNSIGNED DEFAULT NULL, CONSTRAINT FK_C6C44B3423645AE0 FOREIGN KEY (mediaVideo) REFERENCES MEDIA (filename) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C6C44B3430CFAC35 FOREIGN KEY (mediaRessource) REFERENCES MEDIA (filename) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_C6C44B34758FC723 FOREIGN KEY (idCourse) REFERENCES COURSE (idCourse) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C6C44B3423645AE0 ON CHAPTER (mediaVideo)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C6C44B3430CFAC35 ON CHAPTER (mediaRessource)');
        $this->addSql('CREATE INDEX IDX_C6C44B34758FC723 ON CHAPTER (idCourse)');
        $this->addSql('CREATE TABLE CHAPTER_PROGRESS (status VARCHAR(255) NOT NULL, createdAt DATETIME NOT NULL, idUser INTEGER UNSIGNED NOT NULL, idChapter INTEGER UNSIGNED NOT NULL, PRIMARY KEY(idUser, idChapter), CONSTRAINT FK_323B223EFE6E88D7 FOREIGN KEY (idUser) REFERENCES USER (idUser) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_323B223EE938DEDC FOREIGN KEY (idChapter) REFERENCES CHAPTER (idChapter) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_323B223EFE6E88D7 ON CHAPTER_PROGRESS (idUser)');
        $this->addSql('CREATE INDEX IDX_323B223EE938DEDC ON CHAPTER_PROGRESS (idChapter)');
        $this->addSql('CREATE TABLE COURSE (idCourse INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, title VARCHAR(150) NOT NULL, description VARCHAR(250) NOT NULL, visibility VARCHAR(255) NOT NULL, updatedAt DATETIME NOT NULL, createdAt DATETIME NOT NULL, mediaBanner VARCHAR(30) DEFAULT NULL, codeCourseCategory INTEGER UNSIGNED DEFAULT NULL, idUser INTEGER UNSIGNED DEFAULT NULL, CONSTRAINT FK_E666A83FFD1095FC FOREIGN KEY (mediaBanner) REFERENCES MEDIA (filename) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E666A83FDC961AD5 FOREIGN KEY (codeCourseCategory) REFERENCES COURSE_CATEGORY (codeCourseCategory) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E666A83FFE6E88D7 FOREIGN KEY (idUser) REFERENCES USER (idUser) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E666A83FFD1095FC ON COURSE (mediaBanner)');
        $this->addSql('CREATE INDEX IDX_E666A83FDC961AD5 ON COURSE (codeCourseCategory)');
        $this->addSql('CREATE INDEX IDX_E666A83FFE6E88D7 ON COURSE (idUser)');
        $this->addSql('CREATE TABLE COURSE_CATEGORY (codeCourseCategory INTEGER UNSIGNED NOT NULL, label VARCHAR(30) NOT NULL, PRIMARY KEY(codeCourseCategory))');
        $this->addSql('CREATE TABLE COURSE_ENROLLMENT (createdAt DATETIME NOT NULL, idUser INTEGER UNSIGNED NOT NULL, idCourse INTEGER UNSIGNED NOT NULL, PRIMARY KEY(idUser, idCourse), CONSTRAINT FK_D8D31B91FE6E88D7 FOREIGN KEY (idUser) REFERENCES USER (idUser) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_D8D31B91758FC723 FOREIGN KEY (idCourse) REFERENCES COURSE (idCourse) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_D8D31B91FE6E88D7 ON COURSE_ENROLLMENT (idUser)');
        $this->addSql('CREATE INDEX IDX_D8D31B91758FC723 ON COURSE_ENROLLMENT (idCourse)');
        $this->addSql('CREATE TABLE MEDIA (filename VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, mimeType VARCHAR(15) NOT NULL, duration INTEGER UNSIGNED NOT NULL, createdAt DATETIME NOT NULL, PRIMARY KEY(filename))');
        $this->addSql('CREATE TABLE PERMISSION (codePermission INTEGER UNSIGNED NOT NULL, "action" VARCHAR(30) NOT NULL, ressource VARCHAR(30) NOT NULL, PRIMARY KEY(codePermission))');
        $this->addSql('CREATE TABLE ROLE (codeRole INTEGER UNSIGNED NOT NULL, name VARCHAR(20) NOT NULL, label VARCHAR(40) NOT NULL, PRIMARY KEY(codeRole))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_61FC67DE5E237E06 ON ROLE (name)');
        $this->addSql('CREATE TABLE ROLE_HAS_PERMISSION (codeRole INTEGER UNSIGNED NOT NULL, codePermission INTEGER UNSIGNED NOT NULL, PRIMARY KEY(codeRole, codePermission), CONSTRAINT FK_40682A4652100B04 FOREIGN KEY (codeRole) REFERENCES ROLE (codeRole) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_40682A464ECD485F FOREIGN KEY (codePermission) REFERENCES PERMISSION (codePermission) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_40682A4652100B04 ON ROLE_HAS_PERMISSION (codeRole)');
        $this->addSql('CREATE INDEX IDX_40682A464ECD485F ON ROLE_HAS_PERMISSION (codePermission)');
        $this->addSql('CREATE TABLE SESSION (idSession VARCHAR(255) NOT NULL, updatedAt DATETIME NOT NULL, createdAt DATETIME NOT NULL, PRIMARY KEY(idSession))');
        $this->addSql('CREATE TABLE SESSION_DATA (idSessionData INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, dataKey VARCHAR(64) NOT NULL, dataValue VARCHAR(255) NOT NULL, isFlash BOOLEAN DEFAULT 0 NOT NULL, idSession VARCHAR(255) DEFAULT NULL, CONSTRAINT FK_3F71955DC0FDBE26 FOREIGN KEY (idSession) REFERENCES SESSION (idSession) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_3F71955DC0FDBE26 ON SESSION_DATA (idSession)');
        $this->addSql('CREATE TABLE USER (idUser INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, firstname VARCHAR(30) NOT NULL, lastname VARCHAR(30) NOT NULL, email VARCHAR(50) NOT NULL, password VARCHAR(60) NOT NULL, updatedAt DATETIME NOT NULL, createdAt DATETIME NOT NULL, codeRole INTEGER UNSIGNED DEFAULT NULL, CONSTRAINT FK_BB063BFD52100B04 FOREIGN KEY (codeRole) REFERENCES ROLE (codeRole) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BB063BFDE7927C74 ON USER (email)');
        $this->addSql('CREATE INDEX IDX_BB063BFD52100B04 ON USER (codeRole)');
        $this->addSql('CREATE TABLE COURSE_BOOKMARK (idUser INTEGER UNSIGNED NOT NULL, idCourse INTEGER UNSIGNED NOT NULL, PRIMARY KEY(idUser, idCourse), CONSTRAINT FK_92CA394BFE6E88D7 FOREIGN KEY (idUser) REFERENCES USER (idUser) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_92CA394B758FC723 FOREIGN KEY (idCourse) REFERENCES COURSE (idCourse) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('CREATE INDEX IDX_92CA394BFE6E88D7 ON COURSE_BOOKMARK (idUser)');
        $this->addSql('CREATE INDEX IDX_92CA394B758FC723 ON COURSE_BOOKMARK (idCourse)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE CHAPTER');
        $this->addSql('DROP TABLE CHAPTER_PROGRESS');
        $this->addSql('DROP TABLE COURSE');
        $this->addSql('DROP TABLE COURSE_CATEGORY');
        $this->addSql('DROP TABLE COURSE_ENROLLMENT');
        $this->addSql('DROP TABLE MEDIA');
        $this->addSql('DROP TABLE PERMISSION');
        $this->addSql('DROP TABLE ROLE');
        $this->addSql('DROP TABLE ROLE_HAS_PERMISSION');
        $this->addSql('DROP TABLE SESSION');
        $this->addSql('DROP TABLE SESSION_DATA');
        $this->addSql('DROP TABLE USER');
        $this->addSql('DROP TABLE COURSE_BOOKMARK');
    }
}
